env:
  global:
    - secure: SCyQ1W8HnHpJvKSu4tVVooSy6jte/HRXxGK/68yaUvyilMGa+vY/RObWTynQ1oxc/tFFGbl+ayf7JgKREIdE/r3dNleB+2rECL4rTs4TeauDg1vD1rPyvmCAwj4AJFG7uueguM6e1PJdg1lsf9Nmg927BnHUuETAyn3HKvnJA6C9iX46N0M8NUkCC4PT2uBTj7n7HBspG8JGuijzOBSoTYFZCYpkIHsY88j352gnnoI1eFXhacrgaEIDdx+Y9SZpUi15i4wzqNYHngvy8TAIx+5E5FbacMcN5yXR+scwVVG2EVZaHDgQ+nZFoeZiUFVbS6inGoCHhdZdUyj0ZM1SWpftyHC6Spf/jzSB/kTnMdtnqxarci0tkQTEWd8qts5ol08q3n1iOQiTdmFBFFYUoNNj7f5vC6m3M0NB73Pqn7ZfX6VtTqjTiSP2Z68cXHZLcCdsmdYFNqRgVvrsDAhEjAfYJjejVTH5wK8Y7VS1T6U0xPXj5sohUYgzEjLY12PzwiYZWHK4XbEurzEjuo2fTbbKEzSW634KNOyO+DMlrIpyV2Ms40k9Gn4pXaEYz8Keks6QBnifTNtM5uB04ieuHo3j/tyR4iD0kK+q07LMbAKvc4K59YOlKXCgvPc3oA/aM3BWlIzDYvfZGEzNb7wzzKKPf0AZNAVi28PGl2z07l0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/just-domains_web_malwaredomains.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
