env:
  global:
    - secure: SRboKoxQkX+sdLbYeEHqbY09t+3Pik4ASAnkhliBLRZJZ57pdjjwgKvLtmGVi+StleNdSEIktwGTLBuZhQMn3WOE3uqCFtZYOptFzTaH3QhuSAO0vwOh0mTtQp973++dz88nAzqmsTbn7a6ElfTgbf+90Q519ad5KDXTQiGuCBPD1gA9YyrDZ3sU/AZXyjoZj3BvQeeRaILkBtB7BsqpEfqC4VA4/w5kBBWaJ5FOrpXfuxIyibTJkhSZKFg7iNXXmqZiqd0C7POlGugkLWhJwewud5E+5f+5BRAgkPmWG8cSt9nvcpfsrckF9iB4o5piWNKXGvv7KPUpNEyvkPvxbZG5attAQACf14boqMfVvA0CiEdphzSj7R4aqj9liHG+KcocQzEv4C97CcQqsYNQueMLEFkrzoCut+UsA+uEFNG+LvM4hbRMjXQAkBac+7D+G5VFVJpWhbsQLOdMFVzy/y+6aGFKPG1IQ40bwGdeTyLaTuuwGbF0i6qlbJlzHPid1VDCDcNIgRXpRFnB+isYXNNEK8EMLFWPiRyKdjLa92AN308gRvuvw/zsNivcQBgkNp5tfPtVu5pQGIayj0dRYDCY9yF7OtH3dT93NSH7MkA3QAG7r9BvRbheFRhzqqqtYR7fv+4HjXCYz6g3OosyEc9EwSKk6xTHAwTsdg7c2Sk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/just-domains_web_malwaredomains.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
