env:
  global:
    - secure: OLCfmlYe80rygobnc/d2YLiCr7m/NpHOX1RhadeDQYWit4Dh8NrurjkXbGT8vHRczrgt/1Hr5ysg18KpHKJgk9uS8ctTkDvt3mRyH6JQzH+0pCIsGdzv+8O8W50xDVMX6S6QA7Tbg55XbowVkT3CADCDU4dsWWzsNzS70cLgGCtsjA623yUXOSoWEM69y9H3BDy5Aj0sUdM2A/2aDmTYA84i9/IYRl9tAwY/S5L3zB47UhBF9f2bawC7T7KV4bTvYhXDChXgizL1FXMXb05u3EjwF83Gn8lLlao9oJxjk8QzduT2EBfNXhqievm+01vF64IWffSAkmZoAVv5dAUU6PhFuhxk8Yuar9fh6avLOpQaotYUDn944cq8T+72/IVKrD694u6jY5DPTUPmcdOgqfskUYlyR8PCROE3oi/dTHWVW+CSUEYimChEYEjbZL99gXc2laeMIsO6UD87LKN5mrDs9OTlqNrfyzafjF6Jd+S7YbzJfqny8lnGSTXcjizX4m8fetJgd06Ol9H6DvREktnBip8IajnwhCycH9+zuXjZEy5t8KXanc3W/Xqa/g6RgKZ4XTfHSQOR7C//a005XvdOiFMkLMnsskZULL8JVrz4cxSlkIVpD9GfJxV7i/vgWSmCflVuIbKCSBCT0Tv6lA3WKmS2CJPBiIQ7mnB8DFk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/just-domains_web_malwaredomains.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
