env:
  global:
    - secure: kodwkVTnyH31De9pGAsvEgnpuZ0Vb0ek0S+i8JIg1SbqUBskQVGYSY9EEE8Gub7TgU+IsdlKjyUbpwMqWBUbLc5mGK2KLjUgqAvoiKnNIdim6sFIV0AEioCIaYEaD6RaVPQ7tS2+WZy5xjcrAhHyarA9fhELOHQuIyBaytnWulsag7sxh6mDaCUBqe0dT90FFeVOqtGbG9MIaXVb7nb9pueB/uLBBrjHrkN18S7S/XhbMjfFcgFPdA+WQ8CM8ED3XnZhcuCmhHfSg7wXLJS5FL+XkG9WXdkhRzulKyXbDyTQIZBBJRk21S8AePqzNRSBIxNNpNPRr64mCcnJJNefwunhYxryltw1Kl4srfbB3hIvwNqmjVVQFDxamxVNQqXGzcgbf77vtaIxtMfSAYfBVY70I5bOJBTY4AbIWRdarsAN/V7Q0PaA8vwDQ5xb4S6CDLXu1a1mZ8IIJEGzELqw6J6PU7WS3QE+5rOw9FeK7mTmpBfmWnD2e0isYL8Qna6QCNlLHxrWHrFG6gilM+qTrqempeZQW03Aw++b6gUkAAMOEwWbBVZqy05mcLjRs+7/TwzPJEZTJh9kLpm0IxzYGjpuDcayBlSF5vIKE2wwCWW4rLbq48+RiLA6CTJxVlTBP/I9bSr1E3gomBop2aABbHA04ABqgfuX5vooOH0NbIk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/just-domains_web_malwaredomains.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
