addons:
    apt:
        packages:
        - dos2unix
cache:
- pip
dist: xenial
env:
    global:
    -   secure: tFZo/rUAcMptPpa1BGFGgj26wSDDYfSZqhsVl4WQMxj7r4EaWKAIoASrceYpCMeHo/HsQWeEm8Hpi20N79omTyv/LbSJwu6cpZw4d3QRcNPAmAj5RezRwPKV3rxpaF+2FC8Lv7fnPVoXeyF4AL8RwVAAcgCXDObD6EoNysh8uRUaETaDJsWImJjh8t/hkk4dekjvzmFuTy/ll+A+qT1IcdMBFO2z/3LlieQiXW+TFwGIm7jV6VXgmYF4inbt+TKctf9el/ZFIhUQ0+xAU9A1xO9f13uZZzPb5xWDWHbjrVWQo4xhiEytNHyRl8Ud1QimqJhW3NNaY4J8v3zrK8iA/xQSOLXsFXv8IvMaTHSVdWIDppKS6TKCstkNdgBQ5LHPM3wId1430MJc1NzwowCpjTTP+0mKIvv+R93p1ikRiZAhWAEie/ALPY5Wa8D4XF9qyKO4d0rF1aMADpYen/5/YDYRheGPElz28w+EF2jKyYJMtPpoMt/GEu4tC9XjxEC4ifdZZ/6ZiMQYk2lSObtgps4mUl5QwWQQehOK/mVnGyTntHfB17qPRzOPjdi3xllDiYcEJA4BdeW1QBjZjk8K0llZ37tZN+uus83k44Fyb93RJAGdN9DwHNxhXquCFeYkwFcbia7hlc/8mM3lJ0BrConLziaWnkkg1LXdVNjcYmE=
    -   GIT_NAME: Travis CI
    -   GIT_EMAIL: dead-hosts@funilrys.com
    -   TRAVIS_REPO_SLUG: dead-hosts/just-domains_web_malwaredomains.com
    -   GIT_BRANCH: master
    -   UPDATE_ME_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/update_me.py
    -   ADMIN_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/admin.py
    matrix:
    - PYTHON_VERSION="3.7.3"
install:
- export PATH="${HOME}/miniconda/bin:${PATH}"
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p ${HOME}/miniconda
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n launcher-environment python="${PYTHON_VERSION}"
- source activate launcher-environment
- python -VV
- pip --version
- pip install dead-hosts-launcher
language: generic
matrix:
    fast_finish: true
notifications:
    email:
        on_failure: always
        on_success: never
        recipients:
        - dead-hosts@funilrys.com
os:
- linux
python:
- '3.7'
script:
- dead_hosts_launcher --version
- dead_hosts_launcher
sudo: required
