env:
  global:
    - secure: YWPdVxu5FpZKjxprDabSjhy+ztoGHr7SLBncLrNsjZPBHlGF7tOL7Qp4/ByR4lQPCyv+B/n8gA81aDukJTrLGh7hyIWiUkLgohzJjnVS4iFSkMOv87FNuNaB2P9VaAXsxV1u7WfykNTXKhYzB7VKLrdXXsrBFmyc2Mj5tgqrgorBv60wOJTqsya6m6ADUjBAXbRT5py0QeeY3p4Wx9clFy99/6CxUFqcnZqqO+kCONFmYfaAL1CXiw8rbFx8MmQdyvziS4y29mEenq05mrGUMQgnGT/2V0L9czHP0XipbrX4uJYc0vK5CpXk2GS59nBw2qvhjnbz9rhtUJ1Bvw71btPicKckRyhGtAOfUDZ+Nl6ygYDS5KEnUhgtTHZqnRtS0o4dNiilTBDa2ugiv3DsHJDzOMpn1Tb0tJCJwqJlY5dJX0oUigMQMc/OBslJfogID36uugeUq4c151DaDf2b/8LkeFz2oaIwz56mnb25bF6dLTf8G4MW7tIsueQH0ZoPmWADGGaedljU8fTR1RDILC9+YkQ6Lms2///XcJBF18QA8OGr0uu447V2ODO4+2ftccqCrKQs4kLWI99FJXfebtgYgPWDjQhImF0hIP58M2IXeYxRCIQJEjR3pOmtYv1rIXEDT/PRvY2E+l19sS9mOUSF1tdCE6RUw2CE7PhhFvw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/just-domains_web_malwaredomains.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
