env:
  global:
    - secure: Z4Rb7zDoXi4vknfSxhZDNpcxjeKy+0HT8B7JPCpaB2XaEq2wafiZ2P5vU1pW++CsMErKlQbljFa0gNp2x2gy4grKx7Uscp22kOOW8I/1ODmVsZEhR4aFBL54CAONEfIkb40XfgCJV9Xq71kTuwYSVSnSmVzBw+UrCPVwmUKci5JIGbUIcGkplbOXRPAS4N4al59Oh/ZMA6f0djrOBuAtQgnIff6w+2FP2HK1+ztuXiAUXDmMgN9GLkAXdV3PCTeOz8oWwtomyLp6mPCqhlQBa4i0CeZ2juxbFhEXLqv89Koo2nxAWcc8EmNkVjHaVUQcshHqS2OdpKdsFOaBP714HGE8Xp2+vzaLQlRgP53eI6VungyMoUrzhA5PFxGNJx172Cv3DNFJIXowNLIkOCrb/56Y58qR2vRoxcw023zphMKwHC2hPJZN99NF1RN0ij4H0cTXquKQqt/QlhO+oCI5dwtTwDHizoPm0yoRzsBxnovZOvlLgjVOzj3kTZVJwdD/qL3PmjfqNdkDYhwyBiWvX9A1k+1cwY4WjILCerpjAlxWMPXbXR31Ykq/M8FF5XVnmBkEz6XmpoLOXhjRrYMFIa4QKRGzOmArIucSNYOZ2QcBj35P/BvSVIEc7E4uWKgsFaoXZSb89GgZUKGjzYMzR8WUTsf1PVp34vM9FVaiQac=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/just-domains_web_malwaredomains.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
