env:
  global:
    - secure: Te1+SdanB3ifk8IrlUvWvzW9IcCkygUfyoLkbkKK7hqx571yCxwqAVbmHJHA4r7VOsxC/klgecZrSwIwlBnidjxqTvUxvNjiDwUPu6Kp2t810iItJH27tm3vz6A4//sqNp0DtDNxpeV5InG/DLCWIRzicDRqsKk2jcZGNpuj4Ttl7sZSK853ATQ8lE/IqGUJncCG/HI3/XnxVm+lLGzXJueyypvgocZA4LLCSvA/lLbegI9/wWliQK3VLnrHueKD939w20yTf/5wbNlUtqpKJxvBaFi/WzGYE1SKzYSgDH2/tDGF4pcZTWdb9ep3zYGHDiZ8wVlK1E2gcNEHaL6mUiU8NSGm2dtMMGveflweE4zxZMRGPnjPL94rI488x+DvwaGXQTLQm+B/tIs60McfwarskxZUo9FKVtuXaYkMQwqWhQTUjvfACnOMjC6j0IlE+2p6vZ6NKhj/IUqCPMwg5Oubo/+bLPWfx5uw3vfMc/q1pZy09NV29d54/kZNyfr512OcmZ0bSXzjXi+gIY2WiFhsTS5Mo0vFXWvS9aFGSscr2E2liW084GgJ1c2aJrw4r/lZKmrhq6/hR4NeW1UcpUSVivSJfcFZ1bZUP3iXrOpSBJmw74d41XCXlpaSkzn5xntuV8dJR54FGHgovF2nm5eykI5ypERovXoV9Y74Ce8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/just-domains_web_malwaredomains.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
