env:
  global:
    - secure: tFZo/rUAcMptPpa1BGFGgj26wSDDYfSZqhsVl4WQMxj7r4EaWKAIoASrceYpCMeHo/HsQWeEm8Hpi20N79omTyv/LbSJwu6cpZw4d3QRcNPAmAj5RezRwPKV3rxpaF+2FC8Lv7fnPVoXeyF4AL8RwVAAcgCXDObD6EoNysh8uRUaETaDJsWImJjh8t/hkk4dekjvzmFuTy/ll+A+qT1IcdMBFO2z/3LlieQiXW+TFwGIm7jV6VXgmYF4inbt+TKctf9el/ZFIhUQ0+xAU9A1xO9f13uZZzPb5xWDWHbjrVWQo4xhiEytNHyRl8Ud1QimqJhW3NNaY4J8v3zrK8iA/xQSOLXsFXv8IvMaTHSVdWIDppKS6TKCstkNdgBQ5LHPM3wId1430MJc1NzwowCpjTTP+0mKIvv+R93p1ikRiZAhWAEie/ALPY5Wa8D4XF9qyKO4d0rF1aMADpYen/5/YDYRheGPElz28w+EF2jKyYJMtPpoMt/GEu4tC9XjxEC4ifdZZ/6ZiMQYk2lSObtgps4mUl5QwWQQehOK/mVnGyTntHfB17qPRzOPjdi3xllDiYcEJA4BdeW1QBjZjk8K0llZ37tZN+uus83k44Fyb93RJAGdN9DwHNxhXquCFeYkwFcbia7hlc/8mM3lJ0BrConLziaWnkkg1LXdVNjcYmE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/just-domains_web_malwaredomains.com
    - GIT_BRANCH: master
    - UPDATE_ME_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/update_me.py
    - ADMIN_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/admin.py

dist: xenial
sudo: required

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install dead-hosts-launcher

script:
  - dead_hosts_launcher


notifications:
  email:
    recipients:
      - dead-hosts@funilrys.com
    on_success: never
    on_failure: always
