env:
  global:
    - secure: ICDQX7twowB9azKyaIzYw/EjzlfvMnTP6xdlxmLLXa9e9xK7RMtzWXaRTAqgSueB0J41o1WJEwpW6EjDbFWg5Pbwl65bqWcmGyA2//P6CtiVLjl+dRiIoB4GjoKsqkC5HnNMrnxm0mthWwp0jGr3E5ryj5d/op1YODX2DqyOt+Mo5bhPOfsPXg49VDl4eDWCdkK63ajZ7/L2Jr2NVHmuvFMnj04l+8oFI0ec3PKgvF1Izgz985IJkmsRAiHzmVXeJ5iGDB3VtfijqooOy8vl8h4QorTVFhkJ6mOiAbGrpwdhopCHdHRSBjmDXBHVy7EqeC4qpDk0yioZdCl2wqe2vLQE9HJxclJsZuYYuFB2cJ9GT5shL45FNrVQUBihWAO4L3MLOVB/tWnWcbmFJEe70E+GDVurHpZznYbEk9N3l21RCLD7t7jimywvrBX7OqBldcRnhN9LtyQFQ/6R3/VWXsYcGZ8kHlJ1RhouMu42vpr1bRmw2YXFzn1zv3AWk9R79V1zbOlZhnAxpxZReCtnLS/VRJo4MIKiKxiixyyu3dRXbQp6zbEV3lXkX3UWWunXafcviheFxP0S5vgci/3WtIQOIhpps1QNCS3Ojj6DeIeQwisvgmRH9Nxjtm1fzx2alXvrhqkcI01ehvjYHnoCoOM34xyqtO70I62ponjM2a4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/just-domains_web_malwaredomains.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
