env:
  global:
    - secure: HyzrOk2R2KjsXy0QIP+MFLkTm5PDU3h1rQ/5ZmgI9hEotEmRFr6zS0NvdYcHoiEVjYuIKeIXiD940napzvX20W7XJ9hfMChsJvL9nhhmK7OLxoa8v8eAwxVrhDGy4vBW7ZCA5lxh/579KXh8eo4cedeson662j9Oa3PYE3myblXnW7pYlmvMn44RK/uwFEriQ0KSJu7anEIiJqBLQoPgvIDuDX3ottLolPMr4ORcuPggbE7b8otqPg8v3FkpCsEBfShMAYgJ3hVOcvXb33JTXqRnqfjN72BZbH7oXvCpVaFe3bFcB2+mVZzJELJQv/xjZGyjnjCpvO3wUlSGUHzCSyXrtzlJWry2x7R8FikMDMH9hLwSIaadb+BPG7bBsHuZLZsHh0pk46IdyJg0zjKgf/B4X4ZhBxy94lQoxco972JOkcegQ4l+AOAqZSJ4BXoDBxd8XHAb9BIAFmENUadPfNDixZeekPUDdRuq9pHMMtwJIupIfkee3QReccAKH50ifdUf+PC50+kxBZWzELjlhPKZ5A24y/YAF5WhO1jwhsKyU71tqYh4CRmhI7IhLLppTAm/L8bNEkEj/YwlNP3LTM+S0jKJUhXXEPVJeqEm7Pnd0nPrveFBL8ToSdjx2U3HhvHyVrUqAGzlFnf5YOKXhb+gJf4a2LZ2RJQP5ZKH6M8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: funilrys@outlook.com
    - TRAVIS_REPO_SLUG: dead-hosts/just-domains_web_malwaredomains.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - sudo apt-get -y install dos2unix python3-pip python3-yaml
  - pip3 install colorama

script:
  - python3 ./update_me.py

notifications:
  email: false
