env:
  global:
    - secure: yH9sx5ijrvjE/x51M3MDWHDo539YtmOzkGKuR0oKseyaoeu++BB6oGKT5us2+S+Qr7IANVacltR0kUxhgwifQ6CxEsZbcN+/1/rGONwZ2Hxy4+V97TpXsHjxnNw9/s7AGaKB1WRG1IIJA+FRkJgZVO++XAPtBkZSziPhzhh1CaphlI9byMxs5wOqBFGx8kj2Bk4svg+0QWXidAZ2PCPWukIP0IODSljfZB7akxbV+DwVUdM86vUrHDkDsktIGoS9qvx8Nyzs21RK4NDEhGBxyDQ6g+HzibCSdtM6p6kVOGD0Ct9jHp9LwY0gDY3PSzXmXGkZOK91yTTfsMdwa0+lKaMaei3vEwXCj+8yCk2ta9f3F/YxNIZgHcxhbNI5Ewdq9z8RRdUFj37muWyf5DuWjcpL3EU3LfsyjzfSrG7k1aYe4FlBGw1XBqhiCobLIy/hhzWx2r2pRdTJhDRx3ACO9di0BEJ49x8ouDWsMnOi6Zo6xHrZ4HMEncn1LDH6N4k9psIT5d0oF68wtuaqgNYgjYAwPa9egemBq3ds9qAWIdwcyzepz8zarz282lRUo0asDEJNRHTTS6axtyJ06kF3geEy/QtRwJZPrMIy0SPMEUAXWBDTbdGE2Tg22m4K4/jEOoOsO3elDDlOeqnT66Nzm/9oDGB3D+P/TSFswkDl9Fc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/just-domains_web_malwaredomains.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
